/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package notes;

/**
 *
 * @author qngnhat
 */
public class WritingNoteArea extends javax.swing.JFrame {

    /**
     * Creates new form NotesWriter
     */
    public WritingNoteArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        pnlAddNotes = new javax.swing.JPanel();
        btnAddNotes = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnMenu = new javax.swing.JLabel();
        pnlExit = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        pnlMiddle = new javax.swing.JPanel();
        pnlBottom = new javax.swing.JPanel();
        pnlBold = new javax.swing.JPanel();
        btnBold = new javax.swing.JLabel();
        pnlItalic = new javax.swing.JPanel();
        btnItalic = new javax.swing.JLabel();

        pnlMain.setBackground(new java.awt.Color(204, 255, 255));

        pnlTop.setBackground(new java.awt.Color(153, 204, 255));
        pnlTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAddNotes.setBackground(new java.awt.Color(153, 204, 255));

        btnAddNotes.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNotes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddNotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_plus_math_25px.png"))); // NOI18N
        btnAddNotes.setToolTipText("Ghi chú mới");
        btnAddNotes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddNotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNotesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddNotesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddNotesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlAddNotesLayout = new javax.swing.GroupLayout(pnlAddNotes);
        pnlAddNotes.setLayout(pnlAddNotesLayout);
        pnlAddNotesLayout.setHorizontalGroup(
            pnlAddNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlAddNotesLayout.setVerticalGroup(
            pnlAddNotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlTop.add(pnlAddNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlMenu.setBackground(new java.awt.Color(153, 204, 255));

        btnMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_more_20px.png"))); // NOI18N
        btnMenu.setToolTipText("Menu");
        btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlTop.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        pnlExit.setBackground(new java.awt.Color(153, 204, 255));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_20px.png"))); // NOI18N
        btnExit.setToolTipText("Đóng cửa sổ");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlExitLayout = new javax.swing.GroupLayout(pnlExit);
        pnlExit.setLayout(pnlExitLayout);
        pnlExitLayout.setHorizontalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlExitLayout.setVerticalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlTop.add(pnlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        pnlMiddle.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout pnlMiddleLayout = new javax.swing.GroupLayout(pnlMiddle);
        pnlMiddle.setLayout(pnlMiddleLayout);
        pnlMiddleLayout.setHorizontalGroup(
            pnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMiddleLayout.setVerticalGroup(
            pnlMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        pnlBottom.setBackground(new java.awt.Color(153, 204, 255));

        pnlBold.setBackground(new java.awt.Color(153, 204, 255));

        btnBold.setBackground(new java.awt.Color(255, 255, 255));
        btnBold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_bold_20px.png"))); // NOI18N
        btnBold.setToolTipText("Ghi chú mới");
        btnBold.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBold.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBoldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBoldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBoldMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBoldLayout = new javax.swing.GroupLayout(pnlBold);
        pnlBold.setLayout(pnlBoldLayout);
        pnlBoldLayout.setHorizontalGroup(
            pnlBoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBold, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlBoldLayout.setVerticalGroup(
            pnlBoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBold, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlItalic.setBackground(new java.awt.Color(153, 204, 255));

        btnItalic.setBackground(new java.awt.Color(255, 255, 255));
        btnItalic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnItalic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_italic_20px.png"))); // NOI18N
        btnItalic.setToolTipText("Ghi chú mới");
        btnItalic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnItalic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnItalicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnItalicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnItalicMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlItalicLayout = new javax.swing.GroupLayout(pnlItalic);
        pnlItalic.setLayout(pnlItalicLayout);
        pnlItalicLayout.setHorizontalGroup(
            pnlItalicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnItalic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlItalicLayout.setVerticalGroup(
            pnlItalicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnItalic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addComponent(pnlBold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlItalic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBold, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlItalic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNotesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNotesMouseEntered
        // TODO add your handling code here:
//        pnlAddNotes.setBackground(new java.awt.Color(229, 229, 229));
        pnlAddNotes.setBackground(pnlTop.getBackground().darker());
    }//GEN-LAST:event_btnAddNotesMouseEntered

    private void btnAddNotesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNotesMouseExited
        // TODO add your handling code here:
        pnlAddNotes.setBackground(pnlTop.getBackground());
    }//GEN-LAST:event_btnAddNotesMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        pnlExit.setBackground(pnlTop.getBackground().darker());
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        pnlExit.setBackground(pnlTop.getBackground());
    }//GEN-LAST:event_btnExitMouseExited

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        // TODO add your handling code here:
        pnlMenu.setBackground(pnlTop.getBackground().darker());
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        // TODO add your handling code here:
        pnlMenu.setBackground(pnlTop.getBackground());
    }//GEN-LAST:event_btnMenuMouseExited

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnAddNotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNotesMouseClicked
        // TODO add your handling code here:
        WritingNoteArea wna = new WritingNoteArea();
        wna.setVisible(true);
        wna.setLocation(this.getX()+this.getWidth()+5, this.getY());
    }//GEN-LAST:event_btnAddNotesMouseClicked

    private void btnBoldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBoldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBoldMouseClicked

    private void btnBoldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBoldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBoldMouseEntered

    private void btnBoldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBoldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBoldMouseExited

    private void btnItalicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnItalicMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnItalicMouseClicked

    private void btnItalicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnItalicMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnItalicMouseEntered

    private void btnItalicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnItalicMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnItalicMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WritingNoteArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WritingNoteArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WritingNoteArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WritingNoteArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WritingNoteArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddNotes;
    private javax.swing.JLabel btnBold;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnItalic;
    private javax.swing.JLabel btnMenu;
    private javax.swing.JPanel pnlAddNotes;
    private javax.swing.JPanel pnlBold;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlItalic;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMiddle;
    private javax.swing.JPanel pnlTop;
    // End of variables declaration//GEN-END:variables
}
